laravel/vite-plugin

tests/index.test.ts
The test case for prefixes the `base` with `ASSET_URL` only work in the `production` mode.
=> Update test case

src/index.ts
Vite does not currently include CSS entry points in the manifest because the standard approach to loading CSS with Vite is to import it via JavaScript.
The problem with loading CSS via JavaScript with Blade, is that in HMR mode, the CSS is injected into the page via JavaScript, and browsers do not block rendering for this, which leads to a "flash of unstyled content" (FOUC) on every page load. It's not an issue with SPAs because the JavaScript also renders the HTML.
This is not an issue in production because we can determine from the manifest the appropriate `<link rel="stylesheet">` tags to create from any JavaScript entry points.
To solve this in HMR mode, we need to output `<link rel="stylesheet">` tags for CSS, which means we need to specify the CSS files as entry points to the …
=> Add CSS entrypoints to the manifest

src/index.ts, tests/index.test.ts
To avoid a "flash of unstyled content" with server-rendered HTML (i.e. Blade), we need to have a separate CSS entry point rather than importing CSS via a JavaScript entry point.
This PR adds Laravel's default CSS entry point as a default for the plugin, as there is no harm in doing so for SPA applications as well.
=> Add a default CSS entrypoint

src/index.ts
The manifest augmentation added in #9 broke SSR builds because the manifest file isn't typically created in this mode.
This PR addresses this by only augmenting the manifest when the manifest is enabled for the build.
It will also now use the manifest name from the resolved config if it exists.
=> Fix manifest handling in SSR mode

UPGRADE.md, src/index.ts, tests/index.test.ts
To avoid a flash of unstyled content with Blade apps, we needed to specify a CSS entry point so that we can load a `<link rel="stylesheet">` tag in HMR mode.
However, for SPAs, this results in a different flash of unstyled content due to the DOM being updated slightly before the new `<link>` tag is loaded. Therefore it is preferable with SPAs to import the CSS via the JavaScript entry point as we had previously.
Given that it doesn't seem possible to create an optimal experience for both SPAs and Blade apps with the same default entry point(s), this PR removes the default entirely so that they must be specified explicitly.
This will of course be configured appropriatly for the stack by Breeze and Jetstream.
=> Remove default entry point

src/index.ts
This PR improves the exit and signal handling so that exception messages are output to the console.
It also ensures that the handlers are only bound once, as editing the `vite.config.js` file causes Vite to call this hooks again.
Fixes #15
=> Display errors on exit

src/index.ts, tests/index.test.ts
This PR fixes an issue where Vite SSR builds would fail to run due to the ESM Inertia helpers being incorrectly detected as externalizable (I know, right...)
The [`ssr` options](https://vitejs.dev/config/#ssr-options) are experimental/alpha so they aren't included in the type definition, hence the ts-ignores.
https://vitejs.dev/guide/ssr.html#ssr-externals
Tested with Breeze and Jetstream.
=> Prevent SSR build from externalizing Inertia helpers

src/index.ts
This PR fixes an issue where the plugin would output Windows paths to the manifest for CSS files on Windows systems. These paths should always be POSIX style.
See https://vitejs.dev/guide/api-plugin.html#path-normalization
Fixes #19
=> Fix manifest CSS paths on Windows

src/index.ts, tests/index.test.ts
This removes the ziggy alias and pushes the concern back to userland.
=> remove ziggy alias

src/inertia-helpers/index.ts, tests/__data__/dummy.ts, tests/index.test.ts
This pull request updates the `resolvePageComponent` inertia helper to work with the object returned both by the glob and globEager imports.
=> Update resolvePageComponent helper to work with both glob and glogEager

src/index.ts
Vite allows you to pass through a custom option for the envDir.
This is useful in cases where you might have multiple frontend packages and so your vite.config.js is not in the root directory.
This update checks for that config option and if so will use it over the current directory when resolving the APP_URL and laravel version.
=> Use Vite's envDir option if specified

src/index.ts
This PR adds support for Vite's `server.host` setting when writing the address to the hot file.
Fixes #23
=> Respect server.host variable in hot file

src/index.ts
Line I missed when submitting #22.
This will use the custom envDir when resolving the assetUrl to be used as `base` when running a build.
=> Respect envDir when resolving assetUrl

src/index.ts, tests/index.test.ts
This PR helps to address #28.
It allows the user to override the Vite `server` configuration when running inside a Sail container.
=> Allow server configuration to be overriden inside a Sail container

src/index.ts
This PR fixes an issue when a CSS entry point is an empty file.
When this is the case, the manifest is missing the `file` key, which is used to generate the HTML script / link tags.
This fix ensures that there is always a file key present.
Fixes #33
This brings our Vite 2 workaround in alignment with how Vite 3 handles manifest generation for empty CSS files.
=> [0.x] Ensure manifest always contains a file key for CSS sources

src/index.ts
Fixes #36
The `writeBundle()` hook gets called twice when using `@vitejs/plugin-legacy`. The first time is before the manifest has been generated by Vite.
I could not find a reasonable way to determine when writing the legacy bundle, so this change seems like the safest option.
=> [0.x] Fix issue with manifest not existing when the legacy asset bundle occurs

README.md, UPGRADE.md
This PR updates the migration guide as follows:
* Adds semi-colons to example code to be consistent with `laravel/laravel`
* Adds a section on updating the test helpers (`withoutMix()` -> `withoutVite()`)
* Adds a section on migrating Mix aliases.
It also adds a link to the official documentation in the README.
=> [0.x] Documentation updates

src/index.ts
This PR updates the hot file generation to use Vite's [`server.hmr.host`](https://vitejs.dev/config/#server-hmr) config option when specified by the user.
This configuration option is intended to tell the Vite client where to find the HMR server for cases where it is different from [`server.host`](https://vitejs.dev/config/#server-host). I believe it makes sense for us to use it as well.
This probably helps a range of use cases, but specifically, it allows users to run Vite inside a Sail container that is running inside WSL, where the Vite dev server needs to be configured on the container's public address, but where the host machine cannot connect to this same address.
Closes #28
=> Use HMR host when set

UPGRADE.md
This updates the migration guide to use GitHub's new [Markdown notes](https://github.com/github-community/community/discussions/16925):
=> Use GitHub Markdown notes

src/index.ts, tests/index.test.ts
This PR adds `app/View/Components/**` to the global default directories to watch and perform full page reloads for. This is useful as View Components may be entirely specified in the class itself with no blade file.
Additionally, it also exports the default directories so users can utilise the default list and just add their own. Here would be an example of he export usage...
```js
import { defineConfig } from 'vite';
import laravel, { refreshPaths } from 'laravel-vite-plugin';
export default defineConfig({
plugins: [
laravel({
input: [
'resources/css/app.css',
'resources/js/app.js',
],
refresh: [
...refreshPaths,
'app/Http/Livewire/**'
],
}),
],
});
```
=> [0.3.x] Add `app/View/Components/**` to default refresh paths

src/index.ts
Currently, the protocol used for the URL presented to the client (for connecting to Vite dev server) is based on the `server.https` config of the dev server.
`const protocol = server.config.server.https ? 'https' : 'http'`
It is reasonable that a user would want the Vite dev server to run without SSL, but have the client connect using SSL. I use a reverse proxy container in my docker environment which routes traffic to the Laravel Sail containers for a couple different projects. The reverse proxy is responsible for terminating the SSL connection and it in turn communicates with the service container over HTTP.
In this environment, the Vite dev server is running and listening for HTTP from within the Laravel Sail container, but the client needs to communicate with the reverse proxy over …
=> Account for an hmr protocol different than the vite server's protocol

package.json, src/index.ts
This PR drops our custom interface for the one now exported by the full reload package.
See: https://github.com/ElMassimo/vite-plugin-full-reload/pull/5
=> [0.x] Utilise packages exported interface

UPGRADE.md
I recently followed the migration guide to migrate from Laravel mix to Vite. I completed all the steps and ran `sail npm run dev`. Unfortunately, it did not work for me, all I could see was a blank screen and some errors in the browser console. This was because I was using Laravel sail for local development. The issue was pretty simple and I thought it would be worth mentioning in the Upgrade guide.
Vite uses a different port (5173) for HMR compared to Laravel mix (8080), and since the default HMR port in Laravel sail is set to 8080, local development does not work without changing the port mapping in your `docker-compose.yml`.
=> Add note for people using Laravel Sail to get local dev environment working with Vite.

UPGRADE.md, package.json, src/index.ts, tests/index.test.ts
- https://github.com/laravel/laravel/pull/5944
- https://github.com/laravel/breeze/pull/171
- https://github.com/laravel/jetstream/pull/1089
- https://github.com/laravel/docs/pull/8049
- SSR output build has changed extension: `bootstrap/ssr/ssr.mjs`. Although we could force this to remain as `.js`, [it looks like all future enhancements will be around modules](https://vitejs.dev/guide/ssr.html#ssr-format), so I think we should stick with this as the default IMO.
- `globEager` has been deprecated. You should use `import.meta.glob('pattern/here/**', { eager: true })`.
- Vite no longer creates self-signed certificates and need to be manually specified (note: because of this I think there is a reason to now look at adding support for detecting Valet certs as a follow up feature).
See more …
=> [0.4.x] Vite 3 support

src/index.ts, tests/index.test.ts
Due to a [bugfix](https://github.com/vitejs/vite/pull/9146) in version Vite 3.0.1 we now need to revert to referencing the package by name directly in order to have Vite not externalise the helpers.
Fixes: #93
=> Do not externalise inertia helpers

src/index.ts
This PR updates the hot file generation to use Vite's [`server.hmr.port`](https://vitejs.dev/config/#server-hmr) config option when specified by the user.
This configuration option is intended to tell the Vite client where to find the HMR server port for cases where it is different from [`server.port`](https://vitejs.dev/config/#server-port). I believe it makes sense for us to use it as well.
This probably helps a range of use cases, but specifically, it allows users to run Vite inside a Sail container that is running inside WSL, where the Vite dev server needs to be configured on the container's public address, but where the host machine cannot connect to this same address.
Users running Vite inside Sail inside WSL will need to add the following to the `defineConfig` section of their …
=> Use HMR port when specified

src/index.ts
Fixes: https://github.com/laravel/vite-plugin/issues/103
=> [0.5.x] Support both string and integer based IP versions

src/index.ts
Hello, 
I have a project in which i need to work with several env files, and none of them are simply called `.env`. 
I usually chose my env file using the `mode` option of vite.
But, when you run a vite server using `mode` option on an existing env file without a default `.env` file the server crash with this error: 
```
/var/www/Boreal/Upcover/Instances/Upcovel/node_modules/laravel-vite-plugin/dist/index.js:110
server.config.logger.info(`  ${picocolors_1.default.green('➜')}  ${picocolors_1.default.bold('APP_URL')}: ${picocolors_1.default.cyan(appUrl.replace(/:(\d+)/, (_, port) => `:${picocolors_1.default.bold(port)}`))}`);
^
TypeError: Cannot read properties of undefined (reading 'replace')
at Timeout._onTimeout (/var/www/Boreal/Upcover/Instances/Upcovel/node_modules/laravel-vite-plugin/d …
```
=> Allow chosing different env files

.eslintrc.js
A recent PR introduced some trailing whitespace which wasn't obvious when reviewing. I'm not sure why this rule isn't enabled by default in the "recommend" rule set, so this PR enables it.
=> Prevent trailing whitespace

UPGRADE.md
=> Update Vapor helper version

src/index.ts
This PR introduces a new configuration option to specify the location of the hot file. This is really just an escape hatch from our normal conventions.
```js
// vite.config.js
export default defineConfig({
plugins: [
laravel({
hotFile: 'storage/vite.hot',
// ...
}),
],
});
```
```blade
// *.blade.php
{{ Vite::useHotFile(storage_path('vite.hot'))->withEntryPoints(['resources/js/app.js']) }}
```
This PR depends on: https://github.com/laravel/framework/pull/43620
The ability to customise the build directory (as seen in the above linked PR) is already possible without the need for additional changes to the plugin:
```js
// vite.config.js
export default defineConfig({
plugins: [
laravel({
buildDirectory: 'foo/bar',
// ...
}),
],
});
```
```blade
// *.blade.php
{{ …
```
=> [0.5.x] Support customising hot file / build path

.github/workflows/tests.yml, src/index.ts
This PR introduces some nice errors for developers when running the HMR server (`npm run dev`) in known environments where it shouldn't be run, specifically:
- Forge
- Vapor
- Envoyer (see: https://github.com/laravel/envoyer/pull/156)
- Misc Continuous Integration
The ENV check can be overridden:
```sh
LARAVEL_BYPASS_ENV_CHECK=1 npm run dev
```
=> [0.6.x] Fail running HMR in known environments

src/index.ts
By default Vite will "inline" assets that are smaller than 4kb by base64 encoding them.
From a Laravel perspective this can cause issues for Blade apps that are looking to use the `Vite::asset()` helper on small assets.
Blade specific apps could set this to `0` manually, however I also find the inconsistent behaviour as the _default_ strange - even if it is beneficial to SPA style applications. I feel setting this to `0` is a good default for Laravel, while still respecting the user configured value.
The alternative would be to add some magic into the `asset` helper, but I don't think we can generally assume the file will still be in it's pre-bundled location (e.g. resources/images/pixel.png) as apps may clear that stuff out for space reasons (e.g. Serverless).
Encoding at runtime also …
=> [0.6.x] Do not inline small assets, by default

src/index.ts, tests/index.test.ts
This PR adds `lang/**` and `resources/lang/**` to the global default directories to watch in order to perform full reloads when translation are updated
=> [0.7.x] Add `lang` directories to default refresh paths

src/index.ts
This PR introduces a new `valetTls` configuration option to allow developers to use Valet generated certificates on their Mac. This is useful as Vite 3 no longer generates a self signed certificate. Valet also puts certificates into the system keychain, so if you are using Chromium or Safari the experience is seamless. 
Unfortunately Firefox does not seem to read from the system keychain, so you may still need to additionally accept the Valet certificate for the Vite server, as we currently have to.
When setting the configuration option to `true`, the plugin will automatically detect the host by checking the current directory name and appending the configured Valet TLD:
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
export default defineConfig({ …
```
=> [0.6.x] Add config option to utilise Valet TLS certificates

src/index.ts
This PR addresses https://github.com/laravel/vite-plugin/issues/149 by respecting the users' `build.manifest` configuration if provided.
I've conservatively marked this as 0.7 because it could change the behaviour if a user had specified a manifest config, which would previously have been ignored.
=> [0.7] Respect user manifest config

src/index.ts
This PR adds support for loading certificates thanks to paths defined in the environment. 
Currently, in our team, we use `valetTls`, which is very nice for us Valet users. But a member of our team uses Windows and Laragon, and cannot benefit from the configuration. 
With this PR, they will be able to define `VITE_DEV_SERVER_KEY` and `VITE_DEV_SERVER_CERT` in their `.env` with the paths to their Laragon certificates. That way, there is no need to touch `vite.config.ts`, so it can keep being environment-agnostic.
~~Keeping this as a draft to test it on my own Windows machine later~~ - also, not so sure about the variable names: `VITE_*` environment variables are available in the front-end through `import.meta.env`.
=> [0.6.x] Support loading certificates from environment variables

package.json
Fixes this issue we have with the build by upgrading the version of typescript we are using.
Upgraded `vitetest` while I was in there.
=> [0.7.x] Fix node type issue

src/index.ts
This is help users that do actually need to bypass this check.
I would prefer we improve the error message than document the feature.
See: https://github.com/laravel/vite-plugin/issues/164
=> Add info to disable env check to error message

src/index.ts
This PR makes the plugin respect the user config for all remaining options.
It also represents a shift in my mindset for the plugin.
The intention was, and still is, to automatically configure Vite in a way that makes sense for a Laravel project because by default Vite is configured for a standalone JavaScript application.
However, there are some Vite config options that we believed _only_ made sense to be configured in a certain way with Laravel and so we effectively enforced them by always specifying our own value in place of anything from the user config. The thought was that if they don't like how the plugin configures Vite then they don't have to use it. The reality is that this plugin has extra functionality (like creating the hot file) that is a pain to re-implement just to tweak …
=> Respect user config for all config options

package.json
Update dependency `vite-plugin-full-reload` to use `v1.0.5` so `warning "laravel-vite-plugin > vite-plugin-full-reload@1.0.4" has incorrect peer dependency "vite@^2 || ^3".` warning can be fixed.
=> [0.7.x] Update package.json to use vite 4 compatible vite-plugin-full-reload

src/index.ts, tests/index.test.ts
Due to a precedence issue with `??` and `?:`, the user's `base` option is not currently being respected. This PR fixes that to ensure that the users config always takes precedence.
Fixes #185
=> [0.7.x] Respects users base config option

src/index.ts
This exposes a hook that allows developers to transform code in serve mode (`npm run dev`) while giving access to the dev server URL. Transforming code in serve mode is already possible, however the developer does not have access to the dev server url.
This is required for some plugins that assume absolute URLs starting with a `/` will be pointing at the vite dev server, e.g.
```html
```
should be interpreted as
```html
```
Due to the nature of the Laravel integration, these URLs do not point to the Vite dev server; they point to the backend web server, such as Nginx.
There are a number of ways this could be addressed, but I decided on a low level implementation with the config hook to give maximum control so we don't make the wrong assumption with a generalisation.
The issue outlined in …
=> [0.7.x] Provide hook to access dev url while transforming

src/dev-server-index.html
This PR update the laravel doc link so that it automatically jump to the latest doc.
=> [0.7.x] Update laravel doc link

UPGRADE.md, package.json, tsconfig.inertia-helpers.json, tsconfig.json
> tl;dr; This PR brings support for projects using `"type": "modules"` to the Laravel plugin.
In there beginning, of this story at least, there were "CJS" or Common JS modules. CJS was the module system that Node created. It uses `require()` and `modules.export`.
Life was good in Node-land and the developers rejoiced in the streets.
Browsers did not support this standard.
ECMAScript then standardised ES Modules "MJS". This module system uses `import X from './foo'` and `export { X } ` type syntax.
Unfortunately for package maintainers there was now a need to compile both CJS and MJS builds. Some build tools or systems required CJS, while others required MJS.
These were the darkest of days.
After a good while, the ecosystem caught up. MJS and CJS was available for most relevant packages. …
=> [0.7.x] Build MJS and CJS versions of the plugin

package.json
In order to support a TypeScript Vite config file, i.e., `vite.config.ts`, we still need to specify the older type style in the `package.json`. This was dropped when we migrated to modules but turns out for the plugin side of things it is still useful to expose them.
Laravel and none of the starter kits ship with with a TS Vite config, but it would still be nice to support it.
=> [0.7.x] Expose base types

package.json
Fixes https://github.com/laravel/vite-plugin/issues/224
When using linters that are parsing and analysing imports from `package.json` files within the `node_modules` directory, they may fail because the `./inertia-helpers` do not, and never have, ship a CJS version.
Because the tooling is using CJS, it cannot find an appropriate import to use and Node itself fails.
This PR adds a fallback entrypoint for `node`. The entry point, as per the docs, may be CJS or MJS, thus we may just point to out existing MJS built assets.
You can read more about entry points in the node docs: https://nodejs.org/docs/latest-v16.x/api/packages.html#package-entry-points
=> [0.7.x] Ensure 'node' has a fallback type when working with static import linters

UPGRADE.md
Include fix for postcss.config.js when compiling assets
When a user follows the guide in `upgrade.md` to revert back to mix from vite, and then tries to compile they will most likely get an error, this pull request fixes that.
=> fix: compile error following upgrade.md's vite to mix guide

src/index.ts
This PR adds Laravel Herd support, with fallback support to Valet.
The reason for prefering Herd over Valet, has to do with that Valet users are likely to upgrade to Herd, but Herd users aren't as likely to downgrade back to Valet. Simultaneously, when Herd is uninstalled, removing the folder that's being looked up here is part of the required steps, as per https://herd.laravel.com/docs/1/troubleshooting/uninstalling
=> Support Laravel Herd

src/index.ts
This PR only changes functionality when running inside of Laravel Sail.
When determining the URL to place in the hot file we currently fallback to the resolved configuration's `server.host`. The plugin sets the resolved configuration's `server.host` to `0.0.0.0` when running inside of Laravel Sail if no user configured value is present.
This means that `0.0.0.0` will end up in the hot file, by default, when running the Vite server inside of Laravel Sail.
This address is fine within the container and is where the Vite server should listen, however communicating from outside the container via this host can be problematic. Safari on Mac is unable to communicate with this host, while Chrome and Firefox are okay. Additionally, communicating with this host on Windows is a problem across the …
=> [0.8] Fix issue with `0.0.0.0` network resolution

package.json
This PR upgrades Vitest from ^0.25.2 to ^0.34.4 (latest).
The ecosystem-ci failed with https://github.com/vitejs/vite/pull/13944.
I'm not sure what the actual reason is, but it passed locally if I upgraded Vitest. Maybe Vitest was relying on CJS ssr feature in old versions.
I guess there won't be any problem with upgrading it.
=> Upgrade vitest

src/index.ts
When running vite behind a reverse proxy, often you can get into situation where your publicly facing URL differs from the internally served URL, I am running into such an issue. 
My vite server is being served on `http://0.0.0.0:8080`, I am reverse proxying `http://0.0.0.0:8080` (via nginx) over to a domain `example.com`, so the publicly facing URL for my vite server is `https://example.com`. My browser has 0 access to `http://0.0.0.0:8080`, it is on a remote machine inside a container. I only have access to it via the reverse proxy.
This is usually solved by setting the `server.origin: 'https://example.com'` so all assets from vite are pointed to the right domain and location. But this `vite-plugin` does not respect the user configured `server.origin` and renders the plugin unusable in …
=> [0.8.x] Respect vite server.origin in viteDevServerUrl

.github/workflows/tests.yml, UPGRADE.md, import.meta.url-polyfill.js, package.json, src/index.ts, tsconfig.json
=> [1.x] Vite 5

src/inertia-helpers/index.ts, tests/index.test.ts
This PR is an alternative to https://github.com/laravel/vite-plugin/pull/252 and https://github.com/laravel/vite-plugin/pull/259.
It allows the `path` to be a string (current behaviour) or an array (new behaviour).
This enables two features:
1. A "fallback" so that users do not see a "whitescreen of death", where `./Pages/Whoops.vue` is the fallback:
```js
createInertiaApp({
// ...
resolve: (name) => resolvePageComponent([`./Pages/${name}.vue`, './Pages/Whoops.vue'], import.meta.glob('./Pages/**/*.vue')),
});
```
Of course, if the fallback isn't present things can still go wrong.
2. Easier migration from one file type to another without having to deal with error control, e.g., when migrating from `.jsx` to `.tsx`
```js
createInertiaApp({
// ...
resolve: (name) => …
```
=> [0.8.x] Fallback pages

src/index.ts, tests/index.test.ts
This PR adds:
- Valet / Herd certificate auto-detection (✨) and makes it the default for upcoming `1.x` release.
- Ability to opt-out of auto-detection `detectTls: false`.
- CLI output to indicate when the Valet / Herd certificate is being used (when known).
Assume everywhere "Valet" is mentioned that it also applies to "Herd".
This PR allows teams with a mixture of Valet and non-Valet users to configure TLS certificates, without adding additional configuration.
The following standard Laravel plugin config supports both use-cases:
```js
import fs from 'fs'
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
export default defineConfig({
plugins: [
laravel({
input: ['resources/css/app.css', 'resources/js/app.js'],
refresh: true,
}),
],
});
```
For Valet users, …
=> [1.x] Auto detect Valet / Herd TLS certificates
